In [26]:
#Types

In [27]:
'123'

'123'

In [28]:
123.0

123.0

In [29]:
type(123)

int

In [30]:
type(123.0)

float

In [31]:
8 / 2

4.0

In [32]:
type (8 // 2)

int

In [33]:
type (8 / 2)

float

***

# Numpy

***

In [34]:
import numpy as np

In [35]:
L = np.array([[1, 2, 3], [4, 5, 6,], [7, 8, 9]])

In [37]:
print (L)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
L.dtype

dtype('int64')

In [42]:
np.arange(9) .reshape(3, 3) + 1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
np.random.randint(1,7)   #gerara n int n inclui last

5

In [91]:
np.random.randint(1,7, 100)

array([6, 4, 6, 1, 4, 6, 4, 1, 1, 1, 2, 1, 5, 2, 5, 4, 1, 4, 6, 5, 2, 2,
       4, 1, 1, 4, 5, 5, 1, 2, 5, 1, 5, 5, 3, 1, 2, 1, 6, 2, 3, 6, 2, 6,
       6, 6, 1, 4, 6, 2, 4, 4, 6, 6, 4, 2, 1, 1, 5, 5, 5, 4, 1, 4, 3, 3,
       6, 6, 4, 5, 3, 2, 2, 3, 1, 5, 6, 2, 6, 4, 2, 2, 6, 6, 1, 6, 6, 5,
       2, 3, 5, 5, 3, 5, 2, 1, 2, 2, 6, 5])

In [92]:
#rool a die
rolls = np.random.randint(1,7, 100)

In [93]:
# Average roll.
np.mean(rolls)

3.53

In [94]:
# Spread
np.std(rolls)

1.633738045097806

In [104]:
#Likert scale
likert = np.random.randint(1,7, 100)

In [105]:
np.mean(likert)

3.75

In [106]:
# Median
np.median(likert)

4.0